### ISSUE TITLE
Abnormal command

### ISSUE THREAD

**Issue by pengzhengfa** [znsio/perfiz#11]
![image](https://user-images.githubusercontent.com/33858082/125901514-cd5b8f10-0b0a-467d-b86b-d488ecb8f29a.png)
"Docker-compose up-d" is what we use when we use the command, but your document is docker compose up-d, the official is the same as mine, it's really weird, and it doesn't start up

**Comment by harikrishnan83** [comment]
Thanks for reporting the issue @pengzhengfa 

Issue #10 and this are related.

I realised that I was experimenting with [compose cli v2](https://docs.docker.com/compose/cli-command/) and I had not added the checks for this in the CLI or in the documentation.

* I have now moved to "docker-compose" to resolve this
* [Installation Instructions](https://perfiz.com/installation.html#installation) have been updated
* [Perfiz Demo Readme](https://github.com/znsio/perfiz-demo#instructions) has been updated

Please update to [latest version](https://perfiz.com/installation.html#installation) and this should work.

Appreciate your effort.

**Comment by harikrishnan83** [comment]
Resolved with release [0.0.24](https://github.com/znsio/perfiz/releases/tag/0.0.24)
